# v.3.4 -> changed "Marvel Comics" to "Marvel Comics"
# This Python file uses the following encoding: latin-1

imprints = {"!mpact comics":"DC Comics", 
            "12-gauge comics":"Image Comics", 
            "2000 ad":"DC Comics", 
            "2099":"Marvel Publishing",
            "360jam":"360ep",
            "5-d comics":"IDW Publishing",
            "aaa pop comics":"Oni Press", 
            "ac/dc comics":"94 HJY", 
            "ace comics":"Marvel Publishing",
            "action":"Viz Media",
            "action 22":"Édition des Archers",
            "action toys":"Image Comics",
            "adult comics":"Personality Comics, Inc.",
            "adv manga":"A. D. Vision (ADV)",
            "adventure comics":"Malibu Graphics",
            "adventure strips":"Modern Tales",
            "aeon":"MU Press",
            "aftermath":"Devil's Due Publishing",
            "aircel comics":"Malibu Graphics",
            "ajax-farrell":"Excellent Publications",
            "akata":"Delcourt",
            "aladdin paperbacks":"Simon & Schuster",
            "alias enterprises":"Image Comics",
            "all pictures comics":"Whitman",
            "all*star":"DC Comics",
            "alpha affect aka aa comics":"Night Phoenix Press",
            "alterniverse":"Marvel Publishing",
            "amalgam":"Marvel/DC",
            "amalgam comics":"Marvel/DC",
            "amar chitra katha":"India Book House",
            "amaze ink":"SLG Publishing",
            "america's best comics":"DC Comics",
            "american nostalgia library":"Hawk Books Limited",
            "amerotica":"NBM",
            "anarchy studios":"Harris Comics",
            "andromeda publications":"Silver Snail",
            "animerica extra":"Viz Comics",
            "another rabco disaster":"Rabbit Valley",
            "apparat":"Avatar Press",
            "arcana kids":"Arcana Studio",
            "archaia studios press":"Sirius Entertainment",
            "archie adventure series":"Archie Comics",
            "archie comics group":"Fawcett",
            "archie giant series":"Archie Comics",
            "archie romance series":"Archie Comics",
            "arclight pictures international":"Antarctic Press",
            "aria press":"Image Comics",
            "ariel books":"Morning Star",
            "armada":"Acclaim Comics",
            "arthur a. levine books":"Scholastic",
            "artis studios":"Image Comics",
            "astonish books":"Astonish Factory",
            "atomeka":"Tundra Publishing, Ltd.",
            "avalon communications":"American Comics Group(ACG)",
            "avalon studios":"Image Comics",
            "avant-garde entertainment":"Approbation Comics",
            "bang! entertainment":"Antarctic Press",
            "basement comics":"Amryl Entertainment",
            "battlebooks incorporated":"Battlebooks Incorporated",
            "bbc children's books":"BBC",
            "bbc youth & children's magazines":"BBC",
            "berkley/first publishing":"First Comics",
            "best syndicated features":"American Comics Group(ACG)",
            "biblioteca grandes del cómic":"Editorial Planeta-De Agostini",
            "big bang comics":"Image Comics",
            "big kana":"Kana",
            "black library":"Games Workshop",
            "blade comics":"Mag Garden",
            "blanc noir":"Dark Horse Comics",
            "blu":"Tokyopop",
            "blue water productions":"Alias Enterprises",
            "bob burden productions":"Dark Horse Comics",
            "body bag":"Big Entertainment",
            "boffin books":"Claypool Comics",
            "bonanza books":"Crown Publishers",
            "bonelli comics":"Dark Horse Comics",
            "boom! kids":"Boom! Studios",
            "boston comics roundtable":"River Bird Studios",
            "bravura":"Malibu Comics",
            "budgie press":"Cornerstone Design",
            "caliber core":"Caliber Comics",
            "caliber fantasy":"Caliber Comics",
            "canada: comic creation nation":"Zeros 2 Heroes Media",
            "capitol stories":"Charlton",
            "carl hungness publishing":"",
            "carlsen manga!":"Carlsen Comic",
            "carlton books":"Carlton Publishing",
            "carnal comics":"Re-Visionary Press",
            "cartoon network":"DC Comics",
            "chaos comics":"Devil's Due Publishing",
            "chaos! comics deutschland":"mg/publishing/",
            "checkerbpg":"Checker Book Publishing Group",
            "cherry comics":"Tundra Publishing, Ltd.",
            "chicago mail order co.":"Centaur Publications",
            "childrens comics publishers, inc.":"Charlton",
            "chix comix":"Tokyopop",
            "cliffhanger":"Wildstorm",
            "cmx":"DC Comics",
            "cocoro books":"DH Publishing",
            "code 6":"CrossGen Comics",
            "colección viñetas negras":"Glénat Italia",
            "colección viñetas negras":"Glénat España",
            "collins reference":"HarperCollins",
            "comcat comics":"Catalan Communications",
            "comic corporation of america":"Centaur Publications",
            "comic house publications":"Lev Gleason Publications",
            "comic magazines":"Quality Comics",
            "comicart":"Carlsen Comics [GER]",
            "comicart camelot":"Carlsen Comic",
            "comicart el dorado":"Carlsen Comics [GER]",
            "comicart fantasy":"Carlsen Comic",
            "comicart science fiction":"Carlsen Comics [GER]",
            "comicart thriller":"Carlsen Comics [GER]",
            "comicraft":"Active Images",
            "comics culture":"Bethy S.A.",
            "comics forum":"Editorial Planeta-De Agostini",
            "comics' greatest world":"Dark Horse Comics",
            "comicslit":"NBM",
            "community comics":"Alias Enterprises",
            "continuity graphic":"Continuity Comics",
            "coppervale press":"Image Comics",
            "creative fire studio & arrogant media":"Image Comics",
            "creston publications":"American Comics Group (ACG)",
            "crestwood publishing":"Prize Publications",
            "crusade fine arts":"Dark Horse Comics",
            "cryptic magazine":"Image Comics",
            "crystal fractal universe":"Crystal Fractal Comics",
            "crystal fractal visions":"Crystal Fractal Comics",
            "curtis magazines":"Marvel Publishing",
            "cx comics":"Fantagraphics Books",
            "d3 digest":"Devil's Due Publishing",
            "dabel brothers":"Marvel Publishing",
            "dakuwaka productions":"Speakeasy Comics",
            "dark horse books":"Dark Horse Comics",
            "dark horse heroes":"Dark Horse Comics",
            "dark horse manga":"Dark Horse Comics",
            "dark kana":"Kana",
            "darkchylde entertainment":"Darkchylde Entertainment",
            "darkstorm":"Alias Enterprises",
            "day one comics":"Image Comics",
            "dc tv comics":"DC Comics",
            "dc/marvel":"",
            "del rey":"Random House",
            "dem guys":"",
            "dengeki comics":"Mediaworks",
            "desperado publishing":"Image Comics",
            "deux press":"Aurora Publishing",
            "digital broome studios":"Image Comics",
            "digital comics":"Reactor",
            "digital webbing":"Echo 3 Worldwide, LLC",
            "dimestore comics group":"Dimestore Productions",
            "director's cut":"Virgin Comics",
            "dodologo comics":"Susan Ferguson",
            "dogstar press":"Sirius Entertainment",
            "double day":"Bantam Books",
            "dragon comics":"Kadokawa Shoten",
            "dragon lance":"Devil's Due Publishing",
            "dreamwave":"Image Comics",
            "dynabrite comics":"Western Printing Co.",
            "dynamic forces":"Dynamic Forces",
            "echo 3 worldwide":"Digital Webbing",
            "eddie campbell comics":"Top Shelf Productions",
            "editions lilliput":"Les Cartoonistes Dangereux",
            "editor's choice":"Viz Comics",
            "egmont manga & anime(ema)":"Egmont vgs",
            "eh productions":"London Night",
            "elseworlds":"DC Comics",
            "epic comics":"Marvel Publishing",
            "epic":"Marvel Publishing",
            "eros comix":"Fantagraphics Books",
            "eternity comics":"Malibu Comics",
            "eurotica":"NBM",
            "exotica":"Sirius Entertainment",
            "extreme":"Image Comics",
            "eye classics":"Self Made Hero",
            "f5 entertainment":"Image Comics",
            "family comics":"Harvey Comics",
            "famous authors, ltd":"Gilberton Publications",
            "famous funnies":"Eastern Color",
            "fantagraphics books inc.":"Fox Comics",
            "father tree press":"WaRP Graphics",
            "feest":"Ehapa Verlag",
            "fiction factory":"Digital Webbing",
            "fireside":"Simon & Schuster",
            "first second":"Roaring Brook Press",
            "fleetway-quality":"Fleetway",
            "flypaper press":"Image Comics",
            "focus":"DC Comics",
            "forgotten realms":"Devil's Due Publishing",
            "forum":"Editorial Planeta-De Agostini",
            "fox atomic comics":"IDW Publishing",
            "fox atomic comics":"HarperCollins",
            "fractal universe":"Entity/Express",
            "frank comunale":"Charlton",
            "friendly comics":"Personality Comics, Inc.",
            "funny pages press":"Alias Enterprises",
            "gauntlet comics":"Caliber Press",
            "girlamatic":"Modern Tales",
            "gladstone":"Bruce Hamilton Publishing, Inc",
            "glénat manga":"Glénat",
            "gli squali":"Bompiani",
            "gold key":"K K Publications",
            "golden":"Western Printing Co.",
            "gorilla comics":"Image Comics",
            "graphic illusions studios":"Graphic Illusions Studios",
            "graphic smash":"Modern Tales",
            "graphic universe":"Lerner Publishing Group",
            "graphix":"Scholastic",
            "graveyard shift comics":"Webcomics Nation",
            "grupo editorial vid":"Grupo Editorial Vid",
            "hanguk":"Casterman",
            "hanna-barbera cartoons inc.":"Archie Comics",
            "harmony books":"Crown Publishers",
            "harper perennial":"HarperCollins",
            "harpercollins":"Tokyopop",
            "harpercollins children's books":"HarperCollins",
            "harpertrophy":"HarperCollins",
            "harry 'a' chesler":"Quality Comics",
            "harvey comics":"Marvel Publishing",
            "harvey entertainment inc.":"Dark Horse Comics",
            "harvey thriller":"Harvey Comics",
            "helix":"DC Comics",
            "hero initiative":"Marvel Publishing",
            "high risk entertainment":"",
            "hill and wang":"Farrar, Straus and Giroux",
            "historical comics":"Marvel Publishing",
            "hit comics":"Dark Horse Comics",
            "homage comics":"Image Comics",
            "hooligans comics":"Hooligans Comics",
            "hooligans horror comics":"Hooligans Comics",
            "humanoids":"The Humanoids Group",
            "humanoids publishing":"The Humanoids Group",
            "hunter thompson unlimited":"13 Flames Empire",
            "hurricane entertainment":"Image Comics",
            "hustler":"LFP, Inc.",
            "hyperwerks":"Image Comics",
            "i fumetti di urania":"Arnoldo Mondadori Editore",
            "i grandi tascabili":"Bompiani",
            "ibooks manga":"iBooks",
            "ibooks, inc.":"Simon & Schuster",
            "icon":"Marvel Publishing",
            "iconografix":"Caliber Comics",
            "ignatz":"Fantagraphics Books",
            "image central":"Image Comics",
            "impact":"DC Comics",
            "impact books":"F+W Publications",
            "indrajal comics":"Bennet, Coleman & Co",
             "infinities":"Dark Horse Comics",
            "inkubo mag":"E Corp",
            "innocent victim":"Image Comics",
            "insight studios":"Image Comics",
            "interstate publishing corp.":"Atlas Comics",
            "jets comics":"Hakusensha K.K.",
            "johnny dc":"DC Comics",
            "juné manga":"Digital Manga Publishing",
            "k. k. publications":"Western Printing Co.",
            "kenner platinum edition":"DC Comics",
            "king hell":"Tundra Publishing, Ltd.",
            "kiss comics group":"Platinum Studios Comics",
            "kitchen sink comix":"Kitchen Sink Press",
            "klasyka polskiego komiksu":"Egmont Polska",
            "knight books":"Hodder & Stoughton",
            "knockabout":"",
            "kodansha comics":"Kodansha",
            "leaping weasel comics":"Sunshine Publications",
            "legend":"Dark Horse Comics",
            "les humanoïdes associés":"The Humanoids Group",
            "lethargic":"01comics.com",
            "liar comics":"Image Comics",
            "linsner.com":"Image Comics",
            "little archie giant series":"Archie Comics",
            "long courrier":"Dargaud",
            "luv luv press":"Aurora Publishing",
            "lynx studios":"Approbation Comics",
            "m tech":"Marvel Publishing",
            "mad books":"EC Comics",
            "made in":"Kana",
            "magazine management co.":"Marvel Publishing",
            "magnecom":"Rip Off Press",
            "male publishing corp.":"Atlas Comics",
            "malibu":"Marvel Publishing",
            "man of action studios":"Image Comics",
            "manga 18":"A18 Corporation",
            "manga minis":"Tokyopop",
            "manga readers":"Tokyopop",
            "manga shakespeare":"Self Made Hero",
            "mangachapters":"Tokyopop",
            "mangaverse":"Marvel Publishing",
            "mangerotica":"Eros Comix",
            "Marvel Publishing":"Panini Comics Brasil",
            "marvel absurd":"Marvel Publishing",
            "marvel adventures":"Marvel Publishing",
            "marvel age":"Marvel Publishing",
            "marvel comics uk":"Marvel Publishing",
            "marvel deutschland":"Panini Verlag",
            "marvel digital comics":"Marvel Publishing",
            "marvel edge":"Marvel Publishing",
            "marvel france":"Panini Comics",
            "marvel humor":"Marvel Publishing",
            "marvel illustrated":"Marvel Publishing",
            "marvel imports":"Marvel Publishing",
            "marvel interactive":"Marvel Publishing",
            "marvel knights":"Marvel Publishing",
            "marvel magazine group":"Marvel Publishing",
            "marvel mexico":"Editorial Televisa",
            "marvel monster group":"Marvel Publishing",
            "marvel music":"Marvel Publishing",
            "marvel select":"Marvel Publishing",
            "marvel/dc":"",
            "mask noir":"Serpent's Tail",
            "maverick":"Dark Horse Comics",
            "max":"Marvel Publishing",
            "mc2":"Marvel Publishing",
            "mcfarlane":"Image Comics",
            "media blasters press":"Media Blasters",
            "mega marvel":"TM-Semic/Fun Media",
            "metropolitan books":"Henry Holt and Company",
            "midnight sons":"Marvel Publishing",
            "milestone":"DC Comics",
            "minx":"DC Comics",
            "mistrzowie komiksu":"Egmont Polska",
            "mlj":"Archie Comics",
            "modern comics":"Charlton",
            "modern comics":"Millennium Publications",
            "monster comics":"Fantagraphics Books",
            "motown machineworks":"Image Comics",
            "motown productions":"Image Comics",
            "mvcreations":"Image Comics",
            "national maritime center, the":"Entity/Express",
            "national periodical publications":"DC Comics",
            "nelson":"Marvel Publishing",
            "neon lit":"Avon Periodicals",
            "new friday publications":"Lev Gleason Publications",
            "new universe":"Marvel Publishing",
            "new wave":"Harrier",
            "new worlds":"Caliber Comics",
            "next entertainment":"Image Comics",
            "northstar":"Comico",
            "novedades editores":"Marvel Publishing",
            "outlaw entertainment":"Outlaw Entertainment",
            "overstreet":"Overcast Comics",
            "panini books":"Panini",
            "panini comics":"Panini Comics",
            "panini comics":"Panini Verlag",
            "panini manga":"Panini Comics",
            "pantheon books":"Random House",
            "papercutz":"NBM",
            "paradox press":"DC Comics",
            "paragon":"AC Comics",
            "paramount":"Marvel Publishing",
            "penthouse comix":"General Media Communications",
            "perennial library":"",
            "petits livres":"Drawn & Quarterly",
            "philomel books":"Penguin Group",
            "piranha music":"Paisley Park Enterprises Inc.",
            "piranha press":"DC Comics",
            "planet manga":"Panini Verlag",
            "planeta comic":"Planeta comic",
            "platinum editions":"Malibu Graphics",
            "plume":"Penguin Group",
            "prion":"Carlton Publishing",
            "producciones el chango":"Cygnus Comics",
            "promotional publ. co.":"Western Printing Co.",
            "protectors":"Malibu Comics",
            "pulp graphic novel":"Viz Comics",
            "pulsar":"Avatar Press",
            "puppet terrors press":"Puppet Terrors Press",
            "radio comics":"Archie Comics",
            "rainbow books":"Brown Watson Ltd.",
            "randall christopher":"Knm Productions",
            "raw books":"Pantheon Books",
            "raw studios":"Image Comics",
            "ray harryhausen signature series":"Bluewater Comics",
            "razorline":"Marvel Publishing",
            "real comet press, the":"Such A Deal Corporation",
            "realbuzz studios":"Barbour Publishing",
            "rebel sidekick":"01comics.com",
            "red circle":"Archie Comics",
            "red zone":"Antarctic Press",
            "redlight manga":"ComicsOne",
            "redmare productions":"Image Comics",
            "renegade":"Aardvark-Vanaheim",
            "ripley's comics":"Schanes Products",
            "riverhead books":"Penguin Group",
            "roaring studios":"Image Comics",
            "robinson":"Constable & Robinson Ltd",
            "rock 'n' roll comics":"Revolutionary Comics",
            "rocket comics":"Dark Horse Comics",
            "rural home":"Croydon Publishing Co.",
            "rush":"Dramaqueen",
            "sacred grounds productions":"Knight Press",
            "secret invasion #1":"Panini Verlag",
            "secret invasion #2":"Panini Verlag",
            "serializer":"Modern Tales",
            "sexploytation comic group":"Last Gasp",
            "sexy fruit":"Ironcat/I.C. Entertainment",
            "shadowline":"Image Comics",
            "shakti":"Virgin Comics",
            "shhwinng comics":"Silhouette Studios",
            "shojo":"Viz Comics",
            "shojo beat":"Viz Comics",
            "shonen jump":"Viz Comics",
            "shonen jump advanced":"Viz Comics",
            "shonen jump profiles":"Viz Comics",
            "silverhawk productions":"Image Comics",
            "simmons comic group":"IDW Publishing",
            "sin factory":"Radio Comix",
            "single edge studios inc.":"01comics.com",
            "slave labor graphics":"SLG Publishing",
            "soleil":"Marvel Publishing",
            "southpaw publishing":"Axess Comics",
            "spire christian comics":"Fleming H. Revell",
            "spoof comics":"Personality Comics, Inc.",
            "st. martin's griffin":"St. Martin's Press",
            "stan lee's pow! entertainment":"Dark Horse Comics",
            "stan lee's sunday comics":"Komikwerks",
            "star comics":"Marvel Publishing",
            "starblaze graphics":"Donning Company",
            "stone arch":"Capstone Publishers",
            "strange tales":"Marvel Publishing",
            "strawberry":"Seven Seas",
            "strip core":"Forum Ljubljana",
            "studio proteus":"Dark Horse Comics",
            "studio ronin":"DMF",
            "sukker punch comix":"Damage Arts Studio",
            "summ publications":"Stand-Up Multi-Media",
            "super publications":"Harvey Comics",
            "swappers quarterly and almanac":"Baily Publishing Co.",
            "sword in stone productions":"A+",
            "tangent":"DC Comics",
            "tapestry":"Caliber Comics",
            "tekno comix":"Big Entertainment",
            "threshold press":"Comic Cavalcade",
            "thunder's mouth press":"Avalon Publishing Group",
            "tidal wave studios":"Image Comics",
            "tipping cow productions":"Lightning",
            "todd mcfarlane productions":"Image Comics",
            "tokuma comics":"Tokuma Shoten",
            "tokyopop book":"TokyoPop/Mixx",
            "tokyopop manga":"TokyoPop/Mixx",
            "tokyopop manga":"Tokyopop",
            "tokyopop novel":"Tokyopop",
            "tome press":"Caliber Comics",
            "too hip gotta go graphics":"Image Comics",
            "top cow productions":"Image Comics",
            "top dollar comics":"Kitchen Sink Comix",
            "top komiks":"TM-Semic/Fun Media",
            "topps":"Dark Horse Comics",
            "totem":"Editorial Nueva Frontera",
            "touchstone":"Simon & Schuster",
            "tsr":"DC Comics",
            "tsunami":"Marvel Publishing",
            "twilight316 studios":"Ka-Blam Comics",
            "udon":"Devil's Due Publishing",
            "udon entertainment":"Devil's Due Publishing",
            "ultimate":"Marvel Publishing",
            "ultracomics":"Harvey Comics",
            "ultraverse":"Malibu Comics",
            "unbridled ambition":"Eclipse Comics",
            "united printing group":"UPG",
            "upshot graphics":"Fantagraphics Books",
            "venture":"Dark Horse Comics",
            "venus comics":"Antarctic Press",
            "vertigo":"DC Comics",
            "via lettera":"Via Lettera",
            "view askew":"Graphitti Designs",
            "villard books":"Random House",
            "virgin comics/sci-fi":"Virgin Comics",
            "virtual comics":"Byron Preiss Multimedia",
            "visionary comics studios":"Markosia",
            "visual anarchy presents":"CFD Productions",
            "vital":"Quality Comics",
            "vivid comix":"Avatar Press",
            "viz comics":"Eclipse Comics",
            "viz kids":"Viz Media",
            "viz manga heroes":"Viz Comics",
            "viz signature":"Viz Comics",
            "voices":"Virgin Comics",
            "w.d. publications inc.":"Walt Disney Company",
            "walt disney comics":"Gold Key",
            "walt disney educational media company":"Walt Disney Company",
            "white rose":"Ironcat/I.C. Entertainment",
            "whitman":"Western Publishing Company",
            "wild wolf studio":"Wild Wolf Entertainment LLC",
            "wildstorm":"DC Comics",
            "wildstorm signature series":"DC Comics",
            "will eisner library":"DC Comics",
            "william shatner presents":"Bluewater Comics",
            "windjammer":"Valiant Comics",
            "wizard":"Wizard",
            "wm. h. wise & co.":"Remington Morse",
            "wolfrider books":"WaRP Graphics",
            "world comics":"De Agostini",
            "yell! comics":"DK Press",
            "yen press":"Hachette Book Group USA",
            "your guide publications":"Lev Gleason Publications",
            "zongo comics":"Bongo Comics Group",
            "zuda comics":"DC Comics"}