# v.3.4 -> changed "Marvel Comics" to "Marvel Comics"
# This Python file uses the following encoding: utf-8
import clr
import log
import re
from utils import sstr

clr.AddReference('System')
from System import Text
from System.Net import WebException, WebRequest
from System.IO import StreamReader

__MARVEL = "Marvel"
__DC = "DC Comics"
__DARKHORSE = "Dark Horse Comics"

publishers = frozenset([
   __MARVEL,
   __DC, 
   __DARKHORSE,
   "01Comics.com",
   "12 Gates Productions",
   "12-Gauge Comics",
   "1st Amendment Publishing",
   "2-D Graphics",
   "20000 Leagues",
   "2000AD",
   "215 INK",
   "21st Century Sandshark Studios",
   "24 Hour Cynic",
   "2Werk",
   "3 Finger Prints",
   "3-D Zone",
   "3-M",
   "360ep",
   "3DO Comics",
   "3H Productions",
   "4 Winds",
   "5th Panel Comics",
   "801 Media",
   "803 Studios",
   "88 MPH",
   "8th Day Entertainment",
   "9th Circle Studios",
   "A",
   "A D Vision",
   "A Division Of Malibu Graphics",
   "A List Comics",
   "A Silent Comics Inc",
   "A Wave Blue World",
   "A-Plus",
   "A.M. Works",
   "A.R.C.",
   "A10 Comics",
   "AAA Milwaukee",
   "AAA Pop",
   "AC",
   "ADV Manga",
   "AKA Comics",
   "ANIA",
   "APComics",
   "AS Film Inform",
   "Aardvark",
   "Aardwolf Productions",
   "Aazurn",
   "Abaculus",
   "Abacus Press",
   "Abbeville Press",
   "Aberration Press",
   "Abiogenesis Press",
   "Ablaze Media",
   "Abnormal Fun",
   "About Comics",
   "Abril",
   "Absence Of Ink",
   "Absolute Blue Graphics",
   "Absolute Tyrant",
   "Abstract Studio",
   "Ac Collector Classics",
   "Academy Comics Ltd",
   "Acclaim",
   "Ace Comics",
   "Ace Magazines",
   "Ace Publications Inc",
   "Acetylene",
   "Acg",
   "Acid Rain Studios",
   "Acme",
   "Across The Pond Studios",
   "Action Folksinger",
   "Action Planet Comics",
   "Active Images",
   "Active Synapse",
   "Adhesive Comics",
   "Adhouse Books",
   "Adventure",
   "Adversary Comix",
   "Aeon",
   "Aerosol Press",
   "After Hours Press",
   "Afterburn Comics",
   "Aftershock Comics",
   "Age Of Heroes",
   "AiT/Planet Lar",
   "Airbrush",
   "Aircel Publishing",
   "Airship Entertainment",
   "Aja Blu Comix",
   "Ajax",
   "Ajax-Farrell",
   "Akita Shoten",
   "Al Fago Magazines",
   "Alamat Comics",
   "Albert Bonniers F",
   "Albin Michel",
   "Alchemy Studios",
   "Alchemy Texts",
   "Alfabeta",
   "Alias Enterprises",
   "Aliwan Comics",
   "All Thumbs Press",
   "All-Negro Comics",
   "Allers",
   "Allers Forlag",
   "Allied Comics",
   "Almighty Publishing",
   "Alpha Productions",
   "Alpha/Streck Enterprises",
   "Alpine Underground",
   "Alterna Comics",
   "Alternative Press",
   "Alvglans",
   "Amalgam Comics",
   "Amazing Aaron Productions",
   "Amazing Comics",
   "Amazing Creations Ink",
   "Ambrosia Publishing",
   "America&#39;s Best Comics",
   "American Cancer Society",
   "American Comics Group",
   "American Friends Service Committee",
   "American Mule",
   "American Red Cross",
   "American Visuals Corporation",
   "Americanime",
   "Americomics",
   "Amerotica",
   "Amryl Entertainment",
   "Anarchy Studios",
   "Andrews And Mcmeel",
   "Angel Entertainment",
   "Angel Gate Press",
   "Angry Viking Press",
   "Anime Works",
   "Another Rainbow",
   "Antarctic Press",
   "Anti-Ballistic Pixelations",
   "Antimatter",
   "Anubis Press",
   "Anvil",
   "Ape Entertainment",
   "Apocalypse",
   "Apparat",
   "Apple",
   "Approbation Comics",
   "Aragon",
   "Arcade Comics",
   "Arcana Studio",
   "Archaia Studios Press",
   "Archangel Studios",
   "Archie",
   "Archie Adventure Series",
   "Ardden Entertainment",
   "Argo Publications",
   "Aria Press",
   "Aries Publications",
   "Arleigh",
   "Armada",
   "Armageddon Press Inc.",
   "Arnoldo Mondadori Editore",
   "Arrache Coeur",
   "Arrow",
   "Arsenic Lullaby Publishing",
   "Askild",
   "Aspen MLT",
   "Asplunds",
   "Astonish Comics",
   "Astorina",
   "Astronaut Ink",
   "Asuka Comics",
   "Asylum Press",
   "Atari",
   "Atlantic F",
   "Atlantis Studios",
   "Atlas",
   "Atlas Comics",
   "Atomeka Press",
   "Atomic Basement",
   "August House",
   "Austintations",
   "Avalon Communications",
   "Avatar Press",
   "Aviation Comics",
   "Avon",
   "Awesome",
   "Azteca Productions",
   "B",
   "B &amp; H Publishing Group",
   "BBC Books",
   "BC",
   "BKR Comics",
   "BSV - Williams",
   "Baby Tattoo Books",
   "Bad Dog Books",
   "Bad Habit Books",
   "Bad Karma Productions",
   "Bad Press Ltd",
   "Badroach Publications",
   "Bailey Publishing Co",
   "Bakh",
   "Bald Guy Studios",
   "Baldini Castoldi Dalai Editore",
   "Ball Publishing",
   "Ballantine Books",
   "Bam",
   "Banana Tales Press",
   "Bandai Entertainment",
   "Bang! Entertainment",
   "Bantam Books",
   "Barbour Christian Comics",
   "Basement Comics",
   "Bastei Verlag",
   "Battlebooks Incorporated",
   "Baychild Productions",
   "Beanworld Press",
   "Beckett",
   "Belif",
   "Bell Features",
   "Berghs",
   "Berkley Books",
   "Berserker Comics",
   "Best Destiny",
   "Best Friends Publication",
   "Beta 3",
   "Betel",
   "Beyond Time Comic",
   "Big Balloon",
   "Big Bang Comics",
   "Big City Comics",
   "Big Dog Ink",
   "Big Head Press",
   "Big Shot Comics",
   "Big Umbrella",
   "Bioroid Studios",
   "Bishop Press",
   "Black Boar Press",
   "Black Bull",
   "Black Cat Comics",
   "Black Coat Comics",
   "Black Diamond Effect Inc.",
   "Black Eye",
   "Black Library",
   "Black Rock Design",
   "Black ball Comics",
   "Blackline Studios",
   "Blacklist Studios",
   "Blackmore",
   "Blackout",
   "Blackthorne",
   "Bladkompaniet As",
   "Blind Ferret",
   "Blind Wolf",
   "Bliss on Tap Publishing",
   "Bloodfire Studios",
   "Bloody Mary Comics",
   "Blu Manga",
   "Blue Comet Press",
   "Blue King Studios",
   "Bluewater Productions",
   "Bob Ross",
   "Bodog",
   "Bokf",
   "Bokfabriken",
   "Bokomotiv",
   "Bompiani",
   "Bones",
   "Boneyard Press",
   "Bongo",
   "Bonnier Carlsen",
   "Bonniers Juniorf",
   "Boom! Studios",
   "Boundless Comics",
   "Brain Scan Studios",
   "Brainstorm",
   "Brave New Words",
   "Brett&#39;s Comic Pile Publishing",
   "Brick Computer Science Institute",
   "Broadsword Comics",
   "Broadway",
   "Broken Halos",
   "Broken Tree Comics",
   "Broken Voice Comics",
   "Brown Shoe Company",
   "Bruce Hershenson",
   "Bubblehead Publishing",
   "Budget Books",
   "Buffalo Books",
   "Bulletproof Comics",
   "Burlyman Entertainment",
   "Buymetoys.com",
   "C.A.M. Press",
   "C.C.A.S. Publication",
   "C.M.I. Corporativo Mexicano de Impresión",
   "CARNIVAL COMICS",
   "CBG",
   "CEA Casa Editrice Astoria",
   "CFW Enterprises",
   "CMX",
   "Cackling Imp Press",
   "Cafe Digital",
   "Cahaba Producttions",
   "Caliber Comics",
   "California Comics",
   "Cambridge House Publishers",
   "Candle Light Press",
   "Candlewick Press",
   "Canew Ideas",
   "Capcom",
   "Capital Comics",
   "Capitol Stories",
   "Capstone Press",
   "Captain Clockwork",
   "Caption Comics",
   "Carabosse Comics",
   "Carlsen Comics",
   "Carlton Publishing",
   "Carnal Comics",
   "Carnopolis",
   "Carol Ediciones S.A. de C.V.",
   "Cartoon Art",
   "Cartoon Books",
   "Casa Editrice Dardo",
   "Casa Editrice Universo",
   "Casterman",
   "Castle Rain",
   "Catalan Communications",
   "Catastrophic Comics",
   "Catwild Publications",
   "Celebrity",
   "Cellar Door Publishing",
   "Centaur",
   "Central Park Media",
   "Century Publications",
   "Cepim",
   "Cge From",
   "Channel M",
   "Chanting Monks Studios",
   "Chaos! Comics",
   "Chaotic Unicorn Press",
   "Charlton",
   "Checker Book Publishing Group",
   "Cherry",
   "Cherry Comics",
   "Chicago Mail Order Comics",
   "Chick Publications",
   "Children",
   "Chronicle Books",
   "Chuang Yi",
   "Cinebooks",
   "Circle Media",
   "Cirkelf",
   "Claypool Comics",
   "Cliffhanger",
   "Club 408 Graphics",
   "Coffin Comics",
   "Colburn Comics",
   "Colour Comics Pty Ltd",
   "Columbia Comics",
   "Com.X",
   "Comely Comix",
   "Comic Art",
   "Comic Book Legal Defense Fund",
   "Comic Legends Legal Defense Fund",
   "Comic Media",
   "Comico",
   "Comics Interview",
   "Comics Unlimited Inc.",
   "Comicsonair Publications",
   "Commercial Comics",
   "Commercial Signs Of Canada",
   "Committed Comics",
   "Company &amp; Sons",
   "Comunicaciones Graficas Comgraf",
   "Condor Verlag",
   "Coniglio Editore",
   "Conquest Press",
   "Continuity",
   "Continum",
   "Conundrum Press",
   "Corgi",
   "Corriere Della Sera",
   "Crack",
   "Cracked Pepper Productions",
   "Craf Publishers",
   "CrankLeft",
   "Creative Impulse Publishing",
   "Creative One",
   "Creators Edge Press",
   "Creston Publishing Corporation",
   "Critical Mass",
   "Cross Plains Comics",
   "Cross Publications",
   "Crossgen",
   "Crown Publishers",
   "Croydon Publishing",
   "Crusade",
   "Crush Dice Comics Company",
   "Cry For Dawn Productions",
   "Cryptic Press",
   "Crystal Comics",
   "Ctrl Alt Del",
   "Cult Press",
   "Cupples &amp; Leon",
   "Cyberosia Publishing",
   "Cyclone Comics",
   "D. S. Publishing",
   "D.C. Thomson &amp; Co.",
   "DK Publishing",
   "DQU COMICS",
   "DWAP Productions",
   "Dab Enterprises",
   "Dabel Brothers Productions",
   "Dagens Nyheters F",
   "Dagger Enterprises",
   "Daim Press",
   "Dakuwaka Productions",
   "Dancing Elephant Press",
   "Danity Kane Comics",
   "Dare Comics",
   "Dargaud",
   "Dark Elf Designs",
   "Dark Horse Manga",
   "Dark Ocean Studios",
   "Darkchylde Entertainment",
   "Darkmatter",
   "David Mckay",
   "David Miller Studios",
   "Dead Dog",
   "Dead Numbat Productions",
   "DeadBox Art Studio",
   "Deadline Publications Ltd.",
   "Def Con Comics",
   "Defiant",
   "Del Rey",
   "Dell",
   "Delta Verlag",
   "Deluxe",
   "Deluxe Comics",
   "Dennis F",
   "Der Freibeuter",
   "Desperado Publishing",
   "Determined Productions, Inc.",
   "Devil&#39;s Due",
   "Dial &quot;C&quot; for Comics",
   "DigiCube",
   "Digital Manga Distribution",
   "Digital Webbing",
   "Dimension Graphics",
   "Dimestore Productions",
   "Dino Comics",
   "Disney",
   "Diva Graphix",
   "Do Gooder Press",
   "Dobry Komiks",
   "Dolmen Publishing",
   "Dork Storm",
   "Double A Comics",
   "Double Edge Publications",
   "Dover Publications",
   "Dr Master Productions",
   "DrMaster Publications Inc.",
   "Dragon Candy Productions",
   "Dragon Comics",
   "Dragon Lady Press",
   "Dramenon Studios",
   "Drawn",
   "Drawn &amp; Quarterly",
   "Dreamwave Productions",
   "Drumfish Productions",
   "Dupuis",
   "Dynamic Forces",
   "Dynamite",
   "Dynamite Entertainment",
   "E",
   "Eagle Comics",
   "Eastern Color",
   "Eastern Comics",
   "Ec",
   "Echo 3 Worldwide",
   "Eclectic Comix",
   "Eclipse",
   "Eddie Campbell Comics",
   "Eden",
   "Edgewater Comics",
   "Ediciones B",
   "Ediciones José G. Cruz",
   "Ediciones La Cúpula S.L.",
   "Ediciones Latinoamericanas",
   "Ediciones de la Flor",
   "Edifumetto",
   "Ediperiodici",
   "Editions First - Gründ - Dragon d'Or ",
   "Editions La Joie de Lire",
   "Editor",
   "Editora Trama",
   "Editora Vord",
   "Editorial Alfaguara",
   "Editorial Ejea",
   "Editorial Greco (Grupo Editorial Colombiano)",
   "Editorial Icavi Ltda.",
   "Editorial Juventud",
   "Editorial Manuel del Valle",
   "Editorial Novaro",
   "Editorial OEPISA",
   "Editorial Rodriguez",
   "Editorial Televisa",
   "Editorial Toukan",
   "Editorial Tucuman",
   "Editoriale Corno",
   "Editoriale Mercury",
   "Editormex Mexicana",
   "Editrice Cenisio",
   "Editrice Puntozero",
   "Edizioni Alpe",
   "Edizioni Araldo",
   "Edizioni BD",
   "Edizioni San Paolo",
   "Edizioni Star Comics",
   "Edizioni d'Arte ""Lo Scarabeo""",
   "Educomics",
   "Edwin Aprill",
   "Eerie Publications",
   "Egmont",
   "Ehapa Verlag",
   "El Capitan",
   "El Mundo",
   "Electric Spaghetti Comics",
   "Elevenstone Studios",
   "Elite Comics",
   "Elvifrance",
   "Empresa Editora Zig Zag S.A.",
   "Endless Horizons Entertainment",
   "Enemy Transmission",
   "Enigma Comics",
   "Enterbrain",
   "Entity",
   "Entity Comics",
   "Enwill Associates",
   "Epic",
   "Epix",
   "Eros Comix",
   "Esteem Comics",
   "Etc",
   "Eternal",
   "Eternity",
   "Eura Editoriale",
   "Eurotica",
   "Event Comics",
   "Everyman Studios",
   "Evil Twin Comics",
   "Evolution Comics",
   "Excellent Publications",
   "Exploding Albatross Funnybooks",
   "Express",
   "Extreme",
   "F",
   "FC9",
   "Fabel",
   "Factoid Books",
   "False Idol Studios",
   "Famous Funnies",
   "Fandom House",
   "Fangoria",
   "Fantaco",
   "Fantaco Enterprises",
   "Fantagor Press",
   "Fantagraphics",
   "Farrar, Straus, and Giroux",
   "Fathom Press",
   "Fawcett Publications",
   "Feest Comics",
   "Felix Comics Inc.",
   "Femme Fatales Comics",
   "Fenickx Productions",
   "Ferret Press",
   "Fiasco Comics",
   "Fiction House",
   "Fiery Studios",
   "Filmation",
   "Fireman Press LTD.",
   "First",
   "First Salvo",
   "First Second Books",
   "Fishtales Inc Productions",
   "Fishwrap Production",
   "Fitzgerald Publishing Company",
   "Flaming Face Productions",
   "Fleetway",
   "Fluid Friction",
   "Fluide Glacial",
   "Focus",
   "Forbidden Fruit",
   "Formatic",
   "Fortress Publishing",
   "Four Star Publications",
   "Fox",
   "Fox Atomic Comics",
   "Foxtrot",
   "Fragile Press",
   "Frew Publications",
   "Friendly",
   "Frightworld",
   "Full Bleed Studios",
   "Full Circle Publications",
   "Full Impact Comics",
   "Full Stop Media",
   "Fun Publications",
   "Funk-O-Tron",
   "Funnies Inc",
   "Furio Viano Editore",
   "Futabasha Publishers Ltd.",
   "Future Comics",
   "FutureQuake Press",
   "Futuropolis",
   "G &amp; T Enterprises",
   "G. Vincent Edizioni",
   "GG Studio",
   "Galassia",
   "Galaxinovels",
   "Galaxy Publishing",
   "Game Players Comics",
   "Games Workshop",
   "Gangan Comics",
   "Garage Graphix",
   "Gary Philips",
   "Gauntlet Comics",
   "Gaviota",
   "Gearbox Press",
   "Gebers",
   "Gem Publications",
   "Gemestone Publ.",
   "Gemstone",
   "General Electric Company",
   "Generation Comics",
   "Genesis West",
   "Genome Studios",
   "George A. Pflaum",
   "Georgia Straight",
   "Giant in the Playground",
   "Gilberton Publications",
   "Gilmor",
   "Gladstone",
   "Glenat Italia",
   "Globe Communications",
   "Gold Key",
   "Golden Press",
   "Golfing / McCombs",
   "Good Comics, Inc",
   "Gotham Entertainment Group",
   "Granata Press",
   "Grand Central Publishing",
   "Graphic Arts Service, Inc.",
   "Graton Editeur",
   "Gratuitous Bunny Comix",
   "Great Big Comics",
   "Great Publications",
   "Great Smoky Mountains Historical Association",
   "Greater Mercury",
   "Green Man Press",
   "Green Publishing",
   "Grosset And Dunlap, Inc.,",
   "Ground Zero Comics",
   "Grupo Editorial Vid",
   "Guild Publications",
   "Gutsoon",
   "H. C. Blackerby",
   "H. H. Windsor",
   "HB Comics",
   "HELOCK COMICS",
   "HM Communications",
   "Hachette",
   "Hakusensha",
   "Hall Of Heroes",
   "Hallden",
   "Halloween",
   "Hamilton Comics",
   "Hammarstr",
   "Hamster Press",
   "Hand Of Doom Publications",
   "Handelsanst",
   "Happy Comics Ltd.",
   "Harpercollins",
   "Harperperennial",
   "Harrier",
   "Harris Comics",
   "Harry A. Chesler/Dynamic",
   "Harry N. Abrams",
   "Harvey",
   "Harvey Pekar",
   "Hasbro",
   "Hays Entertainment",
   "Headless Shakespeare Press",
   "Heavy Metal",
   "Helix",
   "Helsinki Media",
   "Hemmets Journal Ab",
   "Heretic Press",
   "Hero Comics",
   "Hero Initiative",
   "Hero Universe",
   "Heroic Publishing",
   "Heroscribe Comics!",
   "Hershenson",
   "High Impact Entertainment",
   "High Top",
   "Highwater",
   "Highway 62 Press",
   "Hillman",
   "Holyoke",
   "Homage comics",
   "Hot Comics",
   "Hound Comics",
   "Howard, Ainslee &amp; Co.",
   "Hudson Street Press",
   "Hugh Lauter Levin Associates",
   "Humanoids",
   "Hurricane Entertainment",
   "Hyperwerks",
   "Hyperwrench Productions",
   "I.C.E. Comics",
   "I.W. Publishing",
   "IDW Publishing",
   "INFINITY Publishing",
   "INNFUSION",
   "IPC Magazine Ltd.",
   "Icarus Publications",
   "Ice Kunion",
   "Icon Comics",
   "Ideals Publishing",
   "If Edizioni",
   "Iguana Comics",
   "Illustrated Humor Inc",
   "Image",
   "Immortelle Studios",
   "Impact",
   "Imperium Comics",
   "In the Public Domain",
   "Industrial Services",
   "Infinity Comics",
   "Infinity Studios",
   "Infocom",
   "Innovation",
   "Insomnia Press",
   "International Presse Magazine",
   "Iron Circus Comics",
   "Islas Filipinas Publishing Co.",
   "J",
   "JGM Comics",
   "Jabberwocky Graphix",
   "Jack Rabbit Stewdios",
   "Jademan",
   "Jemi F",
   "Jetpack Press",
   "Jets Comics",
   "Jeunesse Joyeuse",
   "Jochen Enterprises",
   "Joe Deagnon",
   "John Andersson",
   "Jump Back Productions",
   "Jump Comics",
   "JuniorPress BV",
   "Juvee Comics",
   "K",
   "Kadokawa Shoten",
   "Kana",
   "Kathang Indio",
   "Kean Soo",
   "Keenspot Entertainment",
   "Ken Pierce Inc.",
   "Kenzer And Company",
   "Key Publications",
   "KiZoic",
   "King Comics",
   "King Features Syndicate",
   "King Hell",
   "Kirby Publishing Company",
   "Kitchen Sink",
   "Kitty Publications",
   "Kk",
   "Knockabout",
   "Known Associates Press",
   "Kodansha",
   "Krause Publications",
   "Kyle Baker Publishing",
   "L",
   "L. Miller &amp; Son, Ltd",
   "L.F.P.",
   "LFB Luigi F. Bona",
   "La Musardine",
   "La Repubblica / L&#39;Espresso",
   "Lab Rat Productions",
   "Last Gasp",
   "Layne Morgan Media",
   "Le Lombard",
   "Leadbelly Publications",
   "Leader Enterprises",
   "Lee Beardall",
   "Legion Of Evil Press",
   "Lego",
   "Lerner Publishing Group",
   "Les Editions Dargaud",
   "Lev Gleason",
   "Liar Comics",
   "Lightning Comics",
   "Lightspeed Press",
   "Lindblads F",
   "Lindqvists",
   "Linsner.com",
   "Lion Library",
   "Literacy Volunteers Of Chicago",
   "Literary Enterprises",
   "Little, Brown &amp; Co.",
   "Lodestone",
   "Lohman Hills",
   "London Night Studios",
   "Lone Star Press",
   "Lost Cause Productions",
   "Lubrix",
   "Lumen",
   "M. F. Enterprises",
   "MAD Books",
   "MDS Studios",
   "MVCreation",
   "Mad Dog Graphics",
   "Mad Love Publishing",
   "Mad Monkey Press",
   "Maerkle Press",
   "Magazine Enterprises",
   "Magazine Management",
   "Magazzini Salani",
   "Magic Press",
   "Magnus &amp; Bunker",
   "Majestic Entertainment",
   "Major Magazines",
   "Malibu",
   "Malmborg",
   "Manga 18",
   "Mango Comics",
   "Mansion Comics",
   "Manuscript Press",
   "Maple Leaf Publishing",
   "Mark",
   "Markosia",
   "Marsu Productions",
   "Martin L. Greim",
   "Marvel Digital Comics Unlimited",
   "Marvel Knights",
   "Marvel Music",
   "Max",
   "Max Bunker Press",
   "Maximum Press",
   "McCain Ellio&#39;s Comics",
   "McK Publishing",
   "McMann &amp; Tate",
   "Mcfarland",
   "Media Press",
   "Megaton Comics",
   "Memory Lane Publication",
   "Mercury Comics",
   "Metro Comics",
   "Metropolitan Books",
   "Midnight Sons",
   "Mighty Comics",
   "Mighty Pumpkin",
   "Milestone",
   "Millennium Publications",
   "Milson",
   "Mina Editores",
   "Mindgame Press Page One, Inc.",
   "Minx",
   "Mirage",
   "Modern",
   "Mojo Press",
   "Mondial",
   "Monkeysuit Press",
   "Monster Comics",
   "Moonface Press",
   "Moonstone",
   "Morning Star Productions",
   "Mosaik Steinchen F",
   "Motorcycleboy Comics",
   "Mr. Comics",
   "Mu Press",
   "Mulehide Graphics",
   "Murray Comics",
   "NFPA",
   "Naked City",
   "Narwain",
   "Nate Butler",
   "Nation-Wide comics",
   "National Comics Publication",
   "National Comics Publications",
   "National Comics Publishing",
   "National Periodical Publications",
   "National Periodical Publications Inc",
   "Nationella Trafiks",
   "Nbm",
   "Nedor",
   "Neko Press",
   "NeoSun",
   "Neuer Tessloff Verlag",
   "New American Library",
   "New Comics Group",
   "New England Comics",
   "New Media Publications",
   "New Universe",
   "New Worlds",
   "Newsbook Publishing",
   "Newspaper: Funny Pages",
   "Nickel Editions",
   "Nicotat",
   "Night Wynd Enterprises",
   "No Mercy",
   "Noble Comics",
   "Norbert Hethke Verlag",
   "Norma Editorial",
   "Normans",
   "Northstar",
   "Nostalgia Press",
   "Novaris Entertainment",
   "Novedades Editores",
   "Novelty Press",
   "Now",
   "Ocean Comics",
   "Odhams Press",
   "Odyssey Comics",
   "Ok",
   "Oktomica",
   "Olio",
   "Olympian Publishing",
   "Olyoptics",
   "Oni Press",
   "Opal",
   "Orang Utan Comics",
   "Ordfront",
   "Orin Books",
   "Oscar Caesar",
   "Oval Projects Limited",
   "P.F. Volland Company",
   "PSG Publishing House",
   "Pacific",
   "Pacific Comics",
   "Palisades Press",
   "Palliard Press",
   "Pan",
   "Pandora Press",
   "Panini Comics",
   "Pantheon Books",
   "Paper Dragonz",
   "Paper Street Comics",
   "Paper Tiger Comics",
   "Paper Tiger Comix",
   "Papercutz",
   "Papyrus Comics",
   "Paquet",
   "Paradox Press",
   "Parents",
   "Parker Editore",
   "Parody Press",
   "Penguin Group",
   "Penny Farthing",
   "Pentagon Publishing Co",
   "Penthouse Comics",
   "Peregrine Entertainment",
   "Personality",
   "Phelps Publishing",
   "Phi3 Comics",
   "Philomel Books",
   "Phoenix Fire Studios",
   "Picturebox",
   "Pied Piper",
   "Pines Comics",
   "Pingvinf",
   "Pinnacle Comics",
   "Pioneer Books Inc.",
   "Piranha Press",
   "Planet Comics",
   "Planeta DeAgostini",
   "Platinum Studios Comics",
   "Play Press",
   "Playboy Press",
   "Pocket Books",
   "Point G Comics",
   "Politisk Revy",
   "Pop Comics",
   "Popular Press",
   "Poseur Ink",
   "Possum Press",
   "Power Comics",
   "Power Records",
   "Praxis Comics",
   "Premier Magazines",
   "Pride Comics",
   "Primal Paper Comics",
   "Print Mint",
   "Prize",
   "Progressive",
   "Promotora K",
   "Publicaciones Herrerias",
   "Publication Enterprises",
   "Publistrip",
   "Pughouse Press",
   "Pulp Theatre",
   "Pure Imagination",
   "Purrsia",
   "Pyramid Communications",
   "Q Comics",
   "Quality Comics",
   "Quality Periodicals",
   "RAK Graphics",
   "RCS MediaGroup",
   "RDS Comics",
   "RSquared Studios",
   "Rab",
   "Rabbit Valley",
   "Radbu Productions",
   "Radical Publishing",
   "Radio Comics",
   "Radio Comix",
   "Rainbow Media",
   "Raj Comics",
   "Ralston-Purina Company",
   "Random House",
   "Rat Race Comix",
   "Razorline",
   "Real",
   "Real Free Press",
   "Realistic",
   "Realm Press",
   "Rebel Studios",
   "Rebellion",
   "Recollections",
   "Red 5 Comics",
   "Red Circle",
   "Red Clown",
   "Red Eagle Entertainment",
   "Red Top",
   "Redbud Studio",
   "Redhead Comics",
   "Regor Company",
   "Renaissance Press",
   "Renegade",
   "Reprodukt",
   "Revolutionary",
   "Rheem Water Heating",
   "Richters F",
   "Rip Off Press",
   "Rocket North Publishing",
   "Roger Corman&#39;s Cosmic Comics",
   "Ronin Studios",
   "Rooster Teeth Productions",
   "Rorschach Entertainment",
   "Rotopress",
   "Rude Dude Productions",
   "Running Press",
   "Rural Home",
   "Russ Cochran",
   "Rutledge Hill Press",
   "S",
   "SANS Entertainment Comics",
   "SQP",
   "Saalfield Publishing Company",
   "SaberCat Comics",
   "Sackmann Und H",
   "Sacred Mountain",
   "Saint James",
   "Salvatore Taormina editore",
   "Sanoma Uitgevers",
   "Saxon",
   "Say/Bart Productions",
   "Scar Comics",
   "Schibsted",
   "Scholastic Book Services",
   "Schultz",
   "Scrap Pictures",
   "Se-Bladene",
   "Second To Some",
   "Semic As",
   "Semic International",
   "Sergio Bonelli Editore",
   "Seven Seas Entertainment",
   "ShadowLine",
   "Shanda Fantasy Arts",
   "Shibalba Press",
   "Shivae Studios",
   "Shooting Star",
   "Showcase Publications",
   "Shueisha",
   "Sig Feuchtwanger",
   "Signet Books",
   "Silent Devil Productions",
   "Silent Nemesis Workshop",
   "SilverWolf",
   "Silverline",
   "Simon And Schuster",
   "Sin Factory Comix",
   "Sirius Entertainment",
   "Skandinavisk Press",
   "Skatoon Productions",
   "Skywald",
   "Slave Labor",
   "Sleeping Giant Comics",
   "Slg Publishing",
   "Sm",
   "Smithsonian Institution",
   "Soleil",
   "Solson Publications",
   "Son of Sam Productions",
   "Sound &amp; Vision International",
   "Space Goat Productions",
   "Spacedog",
   "Spark Publications",
   "Speakeasy Comics",
   "Special Action Comics",
   "Special Studio",
   "Spectrum Comics",
   "Spilled Milk",
   "Spire Christian Comics",
   "Splitter",
   "Spotlight Comics",
   "Spotlight Publishers",
   "St",
   "St. Johns Publishing Co.",
   "Stampa Alternativa / Nuovi Equilibri",
   "Stanhall",
   "Stanley Publications",
   "Stanmor Publications",
   "Star",
   "Star Publications",
   "Star Reach Publications",
   "Starhead Comix",
   "Stats Etc",
   "Sterling",
   "Stopdragon",
   "Storm Lion Publishing",
   "Story Comics",
   "Straw Dog",
   "Strawberry Jam Comics",
   "Street &amp; Smith",
   "Street And Smith",
   "Street and Steel",
   "Studio 407",
   "Studio Aries",
   "Studio Foglio",
   "Studio Insidio",
   "Studio Ironcat",
   "Super Publishing",
   "Superior Publishers Limited",
   "Sussex Publishing Co",
   "Svenska Serier",
   "Swappers Quarterly And Almanac",
   "T.R.I.B.E. Studio Comics",
   "TSR",
   "Ta Nea",
   "Tangent Comics",
   "Tapestry",
   "Tekno Comix",
   "Tell Tale Publications",
   "Tempo Books",
   "Terminal Press",
   "Terra Major",
   "Terzopoulos",
   "Teshkeel Comics",
   "Tetragrammatron",
   "Th3rd World",
   "The 3-D Zone",
   "The Comic Times, Inc.",
   "The Heritage Collection",
   "The Scream Factory",
   "The Toy Man",
   "Thorby Enterprises",
   "Thoughts",
   "Thrill-House Comics",
   "Thunder Baas",
   "Timeless Journey Comics",
   "Timely",
   "Timely Illustrated Features",
   "Tipografia M. Tomasina",
   "Titan Books",
   "Titan Magazines",
   "Toby",
   "Tokuma Comics",
   "Tokyopop",
   "Tom Doherty Associates",
   "Tom Stacey",
   "Tome Press",
   "Top Cow",
   "Top Shelf",
   "Topps",
   "Torpedo Comics",
   "Toutain Editor",
   "Tower",
   "Tower Books",
   "Transfuzion Publishing",
   "Transmission X Comics",
   "Trepidation Comics",
   "Trident Comics",
   "Trigon",
   "Triumph",
   "Triumphant",
   "Triumphant Comics",
   "Trojan",
   "True Believers Press",
   "True Patriot Studios",
   "Tumble Creek Press",
   "Tundra",
   "Tundra Uk",
   "Tusquets Editores",
   "Twomorrow",
   "Tyler James Comics",
   "UDON",
   "US Department of Health, Education and Welfare",
   "Uitgeverij C.I.C.",
   "Ultimate Comic Group",
   "Ultimate Creations",
   "Ultimate Sports Force",
   "Ultraverse",
   "Ungdomsmissionens V",
   "Unified Field Operations",
   "United Features",
   "Universe",
   "Utslag",
   "Utterly Strange Publications",
   "Valiant",
   "Valve",
   "Vanguard Productions",
   "Vermillon",
   "Verotik",
   "Vertical Inc.",
   "Vertigo",
   "Victor Gollancz Ltd.",
   "Victory",
   "View Askew",
   "Viper Comics",
   "Virgin Comics",
   "Virus Comix",
   "Vittorio Pavesio Productions",
   "Viz",
   "Viz Premiere",
   "Viz Select",
   "Vortex",
   "Vrijbuiter, De",
   "W.T. Grant",
   "WCG",
   "WSOY",
   "Wallace Wood",
   "Walt Disney Company Italia",
   "Warner Books",
   "Warner Brothers",
   "Warp Graphics",
   "Warren",
   "Warrior Publications",
   "Watson-Guptill Publications",
   "Webs Adventure Corporation",
   "Welsh Publishing Group",
   "Western Publishing.",
   "White Buffaloe Press",
   "White Lightning Productions",
   "Whitman",
   "Whitman Publishing",
   "Wicked Good Comics",
   "Wild and Wooly Press",
   "Wildcard Production",
   "Wildstorm",
   "William H Wise",
   "Williams F",
   "Willms Verlag",
   "Windjammer",
   "Winthers",
   "Wisconson Department Of justice",
   "Wizard",
   "Wonder Comix",
   "Work Horse Comics",
   "XL Creations",
   "Xanadu Publishing, Inc.",
   "Yen Press",
   "Yendie Book Publishing",
   "Yoe Studio",
   "Youthful",
   "ZOOLOOK",
   "Zenescope Entertainment",
   "Ziff",
   "Ziff Davis Media",
   "Zip Comics",
   "Zodiac",
   "Zuda Comics",
   "Zuzupetal Press",
   "Zwerchfell",
   "comicsone.com",
   "eBay",
   "ffantasy ffactory",
   "iVerse Media",
   "inZane Comics",
   "mg/publishing",
   "self published",
   "talcMedia Press",
   "¡Ka-Boom! Estudio S.A. de C.V.",
   "�ditions Gl�nat",
])

imprints = {
            "!mpact comics":"DC Comics", 
            "12-gauge comics":"Image Comics", 
            "2000 ad":"DC Comics", 
            "2099":"Marvel Publishing",
            "360jam":"360ep",
            "5-d comics":"IDW Publishing",
            "aaa pop comics":"Oni Press", 
            "ac/dc comics":"94 HJY", 
            "ace comics":"Marvel Publishing",
            "action":"Viz Media",
            "action 22":"ï¿½dition des Archers",
            "action toys":"Image Comics",
            "adult comics":"Personality Comics, Inc.",
            "adv manga":"A. D. Vision (ADV)",
            "adventure comics":"Malibu Graphics",
            "adventure strips":"Modern Tales",
            "aeon":"MU Press",
            "aftermath":"Devil's Due Publishing",
            "aircel comics":"Malibu Graphics",
            "ajax-farrell":"Excellent Publications",
            "akata":"Delcourt",
            "aladdin paperbacks":"Simon & Schuster",
            "alias enterprises":"Image Comics",
            "all pictures comics":"Whitman",
            "all*star":"DC Comics",
            "alpha affect aka aa comics":"Night Phoenix Press",
            "alterniverse":"Marvel Publishing",
            "amalgam":"Marvel/DC",
            "amalgam comics":"Marvel/DC",
            "amar chitra katha":"India Book House",
            "amaze ink":"SLG Publishing",
            "america's best comics":"DC Comics",
            "american nostalgia library":"Hawk Books Limited",
            "amerotica":"NBM",
            "anarchy studios":"Harris Comics",
            "andromeda publications":"Silver Snail",
            "animerica extra":"Viz Comics",
            "another rabco disaster":"Rabbit Valley",
            "apparat":"Avatar Press",
            "arcana kids":"Arcana Studio",
            "archaia studios press":"Sirius Entertainment",
            "archie adventure series":"Archie Comics",
            "archie comics group":"Fawcett",
            "archie giant series":"Archie Comics",
            "archie romance series":"Archie Comics",
            "arclight pictures international":"Antarctic Press",
            "aria press":"Image Comics",
            "ariel books":"Morning Star",
            "armada":"Acclaim Comics",
            "arthur a. levine books":"Scholastic",
            "artis studios":"Image Comics",
            "astonish books":"Astonish Factory",
            "atomeka":"Tundra Publishing, Ltd.",
            "avalon communications":"American Comics Group(ACG)",
            "avalon studios":"Image Comics",
            "avant-garde entertainment":"Approbation Comics",
            "bang! entertainment":"Antarctic Press",
            "basement comics":"Amryl Entertainment",
            "battlebooks incorporated":"Battlebooks Incorporated",
            "bbc children's books":"BBC",
            "bbc youth & children's magazines":"BBC",
            "berkley/first publishing":"First Comics",
            "best syndicated features":"American Comics Group(ACG)",
            "biblioteca grandes del cï¿½mic":"Editorial Planeta-De Agostini",
            "big bang comics":"Image Comics",
            "big kana":"Kana",
            "black library":"Games Workshop",
            "blade comics":"Mag Garden",
            "blanc noir":"Dark Horse Comics",
            "blu":"Tokyopop",
            "blue water productions":"Alias Enterprises",
            "bob burden productions":"Dark Horse Comics",
            "body bag":"Big Entertainment",
            "boffin books":"Claypool Comics",
            "bonanza books":"Crown Publishers",
            "bonelli comics":"Dark Horse Comics",
            "boom! kids":"Boom! Studios",
            "boston comics roundtable":"River Bird Studios",
            "bravura":"Malibu Comics",
            "budgie press":"Cornerstone Design",
            "caliber core":"Caliber Comics",
            "caliber fantasy":"Caliber Comics",
            "canada: comic creation nation":"Zeros 2 Heroes Media",
            "capitol stories":"Charlton",
            "carl hungness publishing":"",
            "carlsen manga!":"Carlsen Comic",
            "carlton books":"Carlton Publishing",
            "carnal comics":"Re-Visionary Press",
            "cartoon network":"DC Comics",
            "chaos comics":"Devil's Due Publishing",
            "chaos! comics deutschland":"mg/publishing/",
            "checkerbpg":"Checker Book Publishing Group",
            "cherry comics":"Tundra Publishing, Ltd.",
            "chicago mail order co.":"Centaur Publications",
            "childrens comics publishers, inc.":"Charlton",
            "chix comix":"Tokyopop",
            "cliffhanger":"Wildstorm",
            "cmx":"DC Comics",
            "cocoro books":"DH Publishing",
            "code 6":"CrossGen Comics",
            "colecciï¿½n viï¿½etas negras":"Glï¿½nat Italia",
            "colecciï¿½n viï¿½etas negras":"Glï¿½nat Espaï¿½a",
            "collins reference":"HarperCollins",
            "comcat comics":"Catalan Communications",
            "comic corporation of america":"Centaur Publications",
            "comic house publications":"Lev Gleason Publications",
            "comic magazines":"Quality Comics",
            "comicart":"Carlsen Comics [GER]",
            "comicart camelot":"Carlsen Comic",
            "comicart el dorado":"Carlsen Comics [GER]",
            "comicart fantasy":"Carlsen Comic",
            "comicart science fiction":"Carlsen Comics [GER]",
            "comicart thriller":"Carlsen Comics [GER]",
            "comicraft":"Active Images",
            "comics culture":"Bethy S.A.",
            "comics forum":"Editorial Planeta-De Agostini",
            "comics' greatest world":"Dark Horse Comics",
            "comicslit":"NBM",
            "community comics":"Alias Enterprises",
            "continuity graphic":"Continuity Comics",
            "coppervale press":"Image Comics",
            "creative fire studio & arrogant media":"Image Comics",
            "creston publications":"American Comics Group (ACG)",
            "crestwood publishing":"Prize Publications",
            "crusade fine arts":"Dark Horse Comics",
            "cryptic magazine":"Image Comics",
            "crystal fractal universe":"Crystal Fractal Comics",
            "crystal fractal visions":"Crystal Fractal Comics",
            "curtis magazines":"Marvel Publishing",
            "cx comics":"Fantagraphics Books",
            "d3 digest":"Devil's Due Publishing",
            "dabel brothers":"Marvel Publishing",
            "dakuwaka productions":"Speakeasy Comics",
            "dark horse books":"Dark Horse Comics",
            "dark horse heroes":"Dark Horse Comics",
            "dark horse manga":"Dark Horse Comics",
            "dark kana":"Kana",
            "darkchylde entertainment":"Darkchylde Entertainment",
            "darkstorm":"Alias Enterprises",
            "day one comics":"Image Comics",
            "dc tv comics":"DC Comics",
            "dc/marvel":"",
            "del rey":"Random House",
            "dem guys":"",
            "dengeki comics":"Mediaworks",
            "desperado publishing":"Image Comics",
            "deux press":"Aurora Publishing",
            "digital broome studios":"Image Comics",
            "digital comics":"Reactor",
            "digital webbing":"Echo 3 Worldwide, LLC",
            "dimestore comics group":"Dimestore Productions",
            "director's cut":"Virgin Comics",
            "dodologo comics":"Susan Ferguson",
            "dogstar press":"Sirius Entertainment",
            "double day":"Bantam Books",
            "dragon comics":"Kadokawa Shoten",
            "dragon lance":"Devil's Due Publishing",
            "dreamwave":"Image Comics",
            "dynabrite comics":"Western Printing Co.",
            "dynamic forces":"Dynamic Forces",
            "echo 3 worldwide":"Digital Webbing",
            "eddie campbell comics":"Top Shelf Productions",
            "editions lilliput":"Les Cartoonistes Dangereux",
            "editor's choice":"Viz Comics",
            "egmont manga & anime(ema)":"Egmont vgs",
            "eh productions":"London Night",
            "elseworlds":"DC Comics",
            "epic comics":"Marvel Publishing",
            "epic":"Marvel Publishing",
            "eros comix":"Fantagraphics Books",
            "eternity comics":"Malibu Comics",
            "eurotica":"NBM",
            "exotica":"Sirius Entertainment",
            "extreme":"Image Comics",
            "eye classics":"Self Made Hero",
            "f5 entertainment":"Image Comics",
            "family comics":"Harvey Comics",
            "famous authors, ltd":"Gilberton Publications",
            "famous funnies":"Eastern Color",
            "fantagraphics books inc.":"Fox Comics",
            "father tree press":"WaRP Graphics",
            "feest":"Ehapa Verlag",
            "fiction factory":"Digital Webbing",
            "fireside":"Simon & Schuster",
            "first second":"Roaring Brook Press",
            "fleetway-quality":"Fleetway",
            "flypaper press":"Image Comics",
            "focus":"DC Comics",
            "forgotten realms":"Devil's Due Publishing",
            "forum":"Editorial Planeta-De Agostini",
            "fox atomic comics":"IDW Publishing",
            "fox atomic comics":"HarperCollins",
            "fractal universe":"Entity/Express",
            "frank comunale":"Charlton",
            "friendly comics":"Personality Comics, Inc.",
            "funny pages press":"Alias Enterprises",
            "gauntlet comics":"Caliber Press",
            "girlamatic":"Modern Tales",
            "gladstone":"Bruce Hamilton Publishing, Inc",
            "glï¿½nat manga":"Glï¿½nat",
            "gli squali":"Bompiani",
            "gold key":"K K Publications",
            "golden":"Western Printing Co.",
            "gorilla comics":"Image Comics",
            "graphic illusions studios":"Graphic Illusions Studios",
            "graphic smash":"Modern Tales",
            "graphic universe":"Lerner Publishing Group",
            "graphix":"Scholastic",
            "graveyard shift comics":"Webcomics Nation",
            "grupo editorial vid":"Grupo Editorial Vid",
            "hanguk":"Casterman",
            "hanna-barbera cartoons inc.":"Archie Comics",
            "harmony books":"Crown Publishers",
            "harper perennial":"HarperCollins",
            "harpercollins":"Tokyopop",
            "harpercollins children's books":"HarperCollins",
            "harpertrophy":"HarperCollins",
            "harry 'a' chesler":"Quality Comics",
            "harvey comics":"Marvel Publishing",
            "harvey entertainment inc.":"Dark Horse Comics",
            "harvey thriller":"Harvey Comics",
            "helix":"DC Comics",
            "hero initiative":"Marvel Publishing",
            "high risk entertainment":"",
            "hill and wang":"Farrar, Straus and Giroux",
            "historical comics":"Marvel Publishing",
            "hit comics":"Dark Horse Comics",
            "homage comics":"Image Comics",
            "hooligans comics":"Hooligans Comics",
            "hooligans horror comics":"Hooligans Comics",
            "humanoids":"The Humanoids Group",
            "humanoids publishing":"The Humanoids Group",
            "hunter thompson unlimited":"13 Flames Empire",
            "hurricane entertainment":"Image Comics",
            "hustler":"LFP, Inc.",
            "hyperwerks":"Image Comics",
            "i fumetti di urania":"Arnoldo Mondadori Editore",
            "i grandi tascabili":"Bompiani",
            "ibooks manga":"iBooks",
            "ibooks, inc.":"Simon & Schuster",
            "icon":"Marvel Publishing",
            "iconografix":"Caliber Comics",
            "ignatz":"Fantagraphics Books",
            "image central":"Image Comics",
            "impact":"DC Comics",
            "impact books":"F+W Publications",
            "indrajal comics":"Bennet, Coleman & Co",
             "infinities":"Dark Horse Comics",
            "inkubo mag":"E Corp",
            "innocent victim":"Image Comics",
            "insight studios":"Image Comics",
            "interstate publishing corp.":"Atlas Comics",
            "jets comics":"Hakusensha K.K.",
            "johnny dc":"DC Comics",
            "junï¿½ manga":"Digital Manga Publishing",
            "k. k. publications":"Western Printing Co.",
            "kenner platinum edition":"DC Comics",
            "king hell":"Tundra Publishing, Ltd.",
            "kiss comics group":"Platinum Studios Comics",
            "kitchen sink comix":"Kitchen Sink Press",
            "klasyka polskiego komiksu":"Egmont Polska",
            "knight books":"Hodder & Stoughton",
            "knockabout":"",
            "kodansha comics":"Kodansha",
            "leaping weasel comics":"Sunshine Publications",
            "legend":"Dark Horse Comics",
            "les humanoï¿½des associï¿½s":"The Humanoids Group",
            "lethargic":"01comics.com",
            "liar comics":"Image Comics",
            "linsner.com":"Image Comics",
            "little archie giant series":"Archie Comics",
            "long courrier":"Dargaud",
            "luv luv press":"Aurora Publishing",
            "lynx studios":"Approbation Comics",
            "m tech":"Marvel Publishing",
            "mad books":"EC Comics",
            "made in":"Kana",
            "magazine management co.":"Marvel Publishing",
            "magnecom":"Rip Off Press",
            "male publishing corp.":"Atlas Comics",
            "malibu":"Marvel Publishing",
            "man of action studios":"Image Comics",
            "manga 18":"A18 Corporation",
            "manga minis":"Tokyopop",
            "manga readers":"Tokyopop",
            "manga shakespeare":"Self Made Hero",
            "mangachapters":"Tokyopop",
            "mangaverse":"Marvel Publishing",
            "mangerotica":"Eros Comix",
            "Marvel Publishing":"Panini Comics Brasil",
            "marvel absurd":"Marvel Publishing",
            "marvel adventures":"Marvel Publishing",
            "marvel age":"Marvel Publishing",
            "marvel comics uk":"Marvel Publishing",
            "marvel deutschland":"Panini Verlag",
            "marvel digital comics":"Marvel Publishing",
            "marvel edge":"Marvel Publishing",
            "marvel france":"Panini Comics",
            "marvel humor":"Marvel Publishing",
            "marvel illustrated":"Marvel Publishing",
            "marvel imports":"Marvel Publishing",
            "marvel interactive":"Marvel Publishing",
            "marvel knights":"Marvel Publishing",
            "marvel magazine group":"Marvel Publishing",
            "marvel mexico":"Editorial Televisa",
            "marvel monster group":"Marvel Publishing",
            "marvel music":"Marvel Publishing",
            "marvel select":"Marvel Publishing",
            "marvel/dc":"",
            "mask noir":"Serpent's Tail",
            "maverick":"Dark Horse Comics",
            "max":"Marvel Publishing",
            "mc2":"Marvel Publishing",
            "mcfarlane":"Image Comics",
            "media blasters press":"Media Blasters",
            "mega marvel":"TM-Semic/Fun Media",
            "metropolitan books":"Henry Holt and Company",
            "midnight sons":"Marvel Publishing",
            "milestone":"DC Comics",
            "minx":"DC Comics",
            "mistrzowie komiksu":"Egmont Polska",
            "mlj":"Archie Comics",
            "modern comics":"Charlton",
            "modern comics":"Millennium Publications",
            "monster comics":"Fantagraphics Books",
            "motown machineworks":"Image Comics",
            "motown productions":"Image Comics",
            "mvcreations":"Image Comics",
            "national maritime center, the":"Entity/Express",
            "national periodical publications":"DC Comics",
            "nelson":"Marvel Publishing",
            "neon lit":"Avon Periodicals",
            "new friday publications":"Lev Gleason Publications",
            "new universe":"Marvel Publishing",
            "new wave":"Harrier",
            "new worlds":"Caliber Comics",
            "next entertainment":"Image Comics",
            "northstar":"Comico",
            "novedades editores":"Marvel Publishing",
            "outlaw entertainment":"Outlaw Entertainment",
            "overstreet":"Overcast Comics",
            "panini books":"Panini",
            "panini comics":"Panini Comics",
            "panini comics":"Panini Verlag",
            "panini manga":"Panini Comics",
            "pantheon books":"Random House",
            "papercutz":"NBM",
            "paradox press":"DC Comics",
            "paragon":"AC Comics",
            "paramount":"Marvel Publishing",
            "penthouse comix":"General Media Communications",
            "perennial library":"",
            "petits livres":"Drawn & Quarterly",
            "philomel books":"Penguin Group",
            "piranha music":"Paisley Park Enterprises Inc.",
            "piranha press":"DC Comics",
            "planet manga":"Panini Verlag",
            "planeta comic":"Planeta comic",
            "platinum editions":"Malibu Graphics",
            "plume":"Penguin Group",
            "prion":"Carlton Publishing",
            "producciones el chango":"Cygnus Comics",
            "promotional publ. co.":"Western Printing Co.",
            "protectors":"Malibu Comics",
            "pulp graphic novel":"Viz Comics",
            "pulsar":"Avatar Press",
            "puppet terrors press":"Puppet Terrors Press",
            "radio comics":"Archie Comics",
            "rainbow books":"Brown Watson Ltd.",
            "randall christopher":"Knm Productions",
            "raw books":"Pantheon Books",
            "raw studios":"Image Comics",
            "ray harryhausen signature series":"Bluewater Comics",
            "razorline":"Marvel Publishing",
            "real comet press, the":"Such A Deal Corporation",
            "realbuzz studios":"Barbour Publishing",
            "rebel sidekick":"01comics.com",
            "red circle":"Archie Comics",
            "red zone":"Antarctic Press",
            "redlight manga":"ComicsOne",
            "redmare productions":"Image Comics",
            "renegade":"Aardvark-Vanaheim",
            "ripley's comics":"Schanes Products",
            "riverhead books":"Penguin Group",
            "roaring studios":"Image Comics",
            "robinson":"Constable & Robinson Ltd",
            "rock 'n' roll comics":"Revolutionary Comics",
            "rocket comics":"Dark Horse Comics",
            "rural home":"Croydon Publishing Co.",
            "rush":"Dramaqueen",
            "sacred grounds productions":"Knight Press",
            "secret invasion #1":"Panini Verlag",
            "secret invasion #2":"Panini Verlag",
            "serializer":"Modern Tales",
            "sexploytation comic group":"Last Gasp",
            "sexy fruit":"Ironcat/I.C. Entertainment",
            "shadowline":"Image Comics",
            "shakti":"Virgin Comics",
            "shhwinng comics":"Silhouette Studios",
            "shojo":"Viz Comics",
            "shojo beat":"Viz Comics",
            "shonen jump":"Viz Comics",
            "shonen jump advanced":"Viz Comics",
            "shonen jump profiles":"Viz Comics",
            "silverhawk productions":"Image Comics",
            "simmons comic group":"IDW Publishing",
            "sin factory":"Radio Comix",
            "single edge studios inc.":"01comics.com",
            "slave labor graphics":"SLG Publishing",
            "soleil":"Marvel Publishing",
            "southpaw publishing":"Axess Comics",
            "spire christian comics":"Fleming H. Revell",
            "spoof comics":"Personality Comics, Inc.",
            "st. martin's griffin":"St. Martin's Press",
            "stan lee's pow! entertainment":"Dark Horse Comics",
            "stan lee's sunday comics":"Komikwerks",
            "star comics":"Marvel Publishing",
            "starblaze graphics":"Donning Company",
            "stone arch":"Capstone Publishers",
            "strange tales":"Marvel Publishing",
            "strawberry":"Seven Seas",
            "strip core":"Forum Ljubljana",
            "studio proteus":"Dark Horse Comics",
            "studio ronin":"DMF",
            "sukker punch comix":"Damage Arts Studio",
            "summ publications":"Stand-Up Multi-Media",
            "super publications":"Harvey Comics",
            "swappers quarterly and almanac":"Baily Publishing Co.",
            "sword in stone productions":"A+",
            "tangent":"DC Comics",
            "tapestry":"Caliber Comics",
            "tekno comix":"Big Entertainment",
            "threshold press":"Comic Cavalcade",
            "thunder's mouth press":"Avalon Publishing Group",
            "tidal wave studios":"Image Comics",
            "tipping cow productions":"Lightning",
            "todd mcfarlane productions":"Image Comics",
            "tokuma comics":"Tokuma Shoten",
            "tokyopop book":"TokyoPop/Mixx",
            "tokyopop manga":"TokyoPop/Mixx",
            "tokyopop manga":"Tokyopop",
            "tokyopop novel":"Tokyopop",
            "tome press":"Caliber Comics",
            "too hip gotta go graphics":"Image Comics",
            "top cow productions":"Image Comics",
            "top dollar comics":"Kitchen Sink Comix",
            "top komiks":"TM-Semic/Fun Media",
            "topps":"Dark Horse Comics",
            "totem":"Editorial Nueva Frontera",
            "touchstone":"Simon & Schuster",
            "tsr":"DC Comics",
            "tsunami":"Marvel Publishing",
            "twilight316 studios":"Ka-Blam Comics",
            "udon":"Devil's Due Publishing",
            "udon entertainment":"Devil's Due Publishing",
            "ultimate":"Marvel Publishing",
            "ultracomics":"Harvey Comics",
            "ultraverse":"Malibu Comics",
            "unbridled ambition":"Eclipse Comics",
            "united printing group":"UPG",
            "upshot graphics":"Fantagraphics Books",
            "venture":"Dark Horse Comics",
            "venus comics":"Antarctic Press",
            "vertigo":"DC Comics",
            "via lettera":"Via Lettera",
            "view askew":"Graphitti Designs",
            "villard books":"Random House",
            "virgin comics/sci-fi":"Virgin Comics",
            "virtual comics":"Byron Preiss Multimedia",
            "visionary comics studios":"Markosia",
            "visual anarchy presents":"CFD Productions",
            "vital":"Quality Comics",
            "vivid comix":"Avatar Press",
            "viz comics":"Eclipse Comics",
            "viz kids":"Viz Media",
            "viz manga heroes":"Viz Comics",
            "viz signature":"Viz Comics",
            "voices":"Virgin Comics",
            "w.d. publications inc.":"Walt Disney Company",
            "walt disney comics":"Gold Key",
            "walt disney educational media company":"Walt Disney Company",
            "white rose":"Ironcat/I.C. Entertainment",
            "whitman":"Western Publishing Company",
            "wild wolf studio":"Wild Wolf Entertainment LLC",
            "wildstorm":"DC Comics",
            "wildstorm signature series":"DC Comics",
            "will eisner library":"DC Comics",
            "william shatner presents":"Bluewater Comics",
            "windjammer":"Valiant Comics",
            "wizard":"Wizard",
            "wm. h. wise & co.":"Remington Morse",
            "wolfrider books":"WaRP Graphics",
            "world comics":"De Agostini",
            "yell! comics":"DK Press",
            "yen press":"Hachette Book Group USA",
            "your guide publications":"Lev Gleason Publications",
            "zongo comics":"Bongo Comics Group",
            "zuda comics":"DC Comics"
}

if __name__ == '__main__':
   log.debug()
   cv_publishers = set()
   for i in range(1, 50):
      try:
         request = WebRequest.Create(
            'http://www.comicvine.com/publishers/?page='
            + sstr(i) + '&sort=alphabetical')
         response = request.GetResponse()
         responseStream = response.GetResponseStream()
         reader = StreamReader(responseStream, Text.Encoding.UTF8)
         page = reader.ReadToEnd()
         matches =re.findall("(?m)<td[^>]*>\s*<a[^>]*>([^<]*)</a>\s*</td>",page)
         cv_publishers.update( m.strip() for m in matches )
         print"Page " + sstr(i) + ", " + sstr(len(matches)) + " publishers..."
         if ( len(matches) != 100 ):
            break
      except WebException, wex:
         print("unexpected web exception: " + str(wex)) 
      finally:
         if 'reader' in vars(): reader.Close()
         if 'responseStream' in vars(): responseStream.Close()
         if 'response' in vars(): response.Close()
         
#   for imprint in imprints:
#      if imprint not in cv_publishers:
#         print("Not in ComicVine: " + imprint)
#         
#   for publisher in publishers:
#      if publisher not in cv_publishers:
#         print("Not in ComicVine: " + publisher)
         
   for cv_pub in sorted(cv_publishers):
      if cv_pub not in imprints and cv_pub not in publishers:
         print('"' + cv_pub + '",')
         